### ISSUE TITLE
Instantiate routes via the container?

### ISSUE THREAD

**Issue by lukemelia** [machty/ember-navigator#9]
In our app, we're subclassing mounted router to instantiate routes via the container rather than "new"-ing them into being. This allows for our routes to have services injected, such as the ember-data or orbit store.

Should this be the default behavior?

**Comment by knownasilya** [comment]
Would love to see what this looks like.

**Comment by lukemelia** [comment]
Here's approximately how we do it:
https://github.com/yapplabs/ember-navigator-nav-stack-demo/blob/master/app/services/navigator-router.js#L12-L21
https://github.com/yapplabs/ember-navigator-nav-stack-demo/blob/master/app/utils/navigator.js#L36-L49

**Comment by lukemelia** [comment]
Per discussion with @machty, we'll proceed to a PR that makes this the default with an escape valve. The container "type" will be `navigator-route`
